### PR TITLE
SSH config file parser: Recognize multiple host names in a "Host" line

### PR DESCRIPTION
**Pull request by Tblue**
Currently, rofi's SSH config file parser only recognizes a *single* host name in a `Host` line when parsing the user's SSH config file. Consequently, the following block yields a single host name, "milliways":

```
Host milliways slartibartfast slarti
    Port 1234
```

However, rofi should present all three host names to the user, i. e. "milliways", "slartibartfast" and "slarti".

This patch modifies the config file parser so that it correctly recognizes multiple host names in a `Host` line. Additionally, it also makes the parser ignore comment lines and negated patterns.

### CODE REVIEW

**Comment by DaveDavenport** [comment]
You are right.  Patch looks good on first glance, one minor suggestion: Can you change str(n)dup to g_str(n)dup.  The non-glib strndup is not always available.

**Comment by Tblue** [comment]
Done. I also changed `strcasecmp()` to `g_ascii_strcasecmp()` since if I remember correctly, the former is not always available either. Using glib's ASCII version is probably okay, since host names usually are plain ASCII.

**Comment by DaveDavenport** [comment]
If people complain we can always switch to g_utf8_collate.

I will merge the patch this evening.

**Comment by Tblue** [comment]
All right. Thanks!

**Pull request merged**
