### PR TITLE
typo in install docs

### PR DESCRIPTION
**Pull request by geier**

### CODE REVIEW

**Comment by DaveDavenport** [comment]
Read the manual carefully, the `../configure` is correct for the given instructions.
The way explained in the install instructions builds the source in a separate directory (named build) and therefor does not pollute the source directory.  The actual configure script is in the parent directory.

**Comment by DaveDavenport** [comment]
owh there is an error..  I forgot the cd build..  my bad :(
Will fix that.

**Comment by geier** [comment]
Oh, looks like I didn't think about *why* the build directory is created (and didn't notice that it stayed empty)...

**Comment by DaveDavenport** [comment]
Thanks for reporting, it is good to have these things squashed. I am pretty bad at this. Added the `cd build` to the install guide.

**Pull request closed without merging**
