### PR TITLE
Add updated gruvbox themes

### PR DESCRIPTION
**Pull request by bardisty**
This adds updated gruvbox rasi themes. Mostly a refactor and small changes from the current generated versions such as padding, border size, prompt colon, and colors are easier for users to customize if they wish.

I've also opened a PR for this on the `rofi-themes` repo:
https://github.com/DaveDavenport/rofi-themes/pull/16

### CODE REVIEW

**Comment by bardisty** [comment]
@sardemff7 Everything below the global `* { }` section is the same between themes.

**Comment by DaveDavenport** [comment]
We could have an gruvbox-common.rasi that is included by every theme?
(I should check if we can include a gruvbox-common.inc, will check that later).

**Comment by bardisty** [comment]
> We could have an gruvbox-common.rasi that is included by every theme?

Just pushed this. Easy revert if you guys end up not wanting to go that route.

**Comment by DaveDavenport** [comment]
@carnager  Did we merge this already?

**Comment by DaveDavenport** [comment]
I think this was merged another way around at some point.. if not, please let me know.

**Pull request closed without merging**
