### PR TITLE
Use correct namelen when connecting to i3 socket

### PR DESCRIPTION
**Pull request by t6**
This mirrors what i3 itself does and fixes i3 support on FreeBSD.

### CODE REVIEW

**Comment by DaveDavenport** [comment]
I copied this from a working example. I changed ti for a reason, I cannot remember why though, Ill try to remember.

**Comment by t6** [comment]
I've seen it in Beej's Guide like this: http://beej.us/guide/bgipc/output/html/multipage/unixsock.html#sockclient

But the man pages for connect(2) on FreeBSD and [OpenBSD](http://www.openbsd.org/cgi-bin/man.cgi/OpenBSD-current/man2/connect.2?query=connect) imply that this is wrong.

Here is how i3 does it:
```c
    struct sockaddr_un addr;
    memset(&addr, 0, sizeof(struct sockaddr_un));
    addr.sun_family = AF_LOCAL;
    strncpy(addr.sun_path, socket_path, sizeof(addr.sun_path) - 1);
    if (connect(sockfd, (const struct sockaddr *)&addr, sizeof(struct sockaddr_un)) < 0)
        err(EXIT_FAILURE, "Could not connect to i3");
```

**Comment by DaveDavenport** [comment]
Thanks for the info.  It seems to work fine  (nice travis is broken).

**Comment by DaveDavenport** [comment]
Thanks for the patch.

**Pull request merged**
